sudo: false
language: python
python:
  #- "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO="18" layer="IPC"
  - DJANGO="18" layer="redis"
  - DJANGO="19" layer="IPC"
  - DJANGO="19" layer="redis"
  - DJANGO="110" layer="IPC"
  - DJANGO="110" layer="redis"
  - DJANGO="110" layer="rabbit"
services:
  - redis-server
  - rabbitmq
install: pip install tox-travis
script: tox